# Generated by Django 5.2.4 on 2025-10-02 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('card_id', models.UUIDField()),
                ('streak', models.PositiveIntegerField(default=0)),
                ('last_interval_seconds', models.PositiveIntegerField(default=0)),
                ('next_review_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'next_review_at'], name='scheduler_c_user_id_a1d049_idx')],
                'unique_together': {('user_id', 'card_id')},
            },
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('card_id', models.UUIDField()),
                ('rating', models.SmallIntegerField()),
                ('idempotency_key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_review_at', models.DateTimeField()),
                ('next_interval_seconds', models.PositiveIntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'card_id', 'created_at'], name='scheduler_r_user_id_7d6aef_idx')],
                'unique_together': {('user_id', 'card_id', 'idempotency_key')},
            },
        ),
    ]
